import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-icon-demo',
  templateUrl: './icon-demo.component.html',
  styleUrls: ['./icon-demo.component.scss'],
  standalone: true,
  imports: [CommonModule]
})
export class IconDemoComponent {
  icons = [
    { name: 'Air Balloon', class: 'nc-air-baloon' },
    { name: 'Album', class: 'nc-album-2' },
    { name: 'Alert Circle', class: 'nc-alert-circle-i' },
    { name: 'Align Center', class: 'nc-align-center' },
    { name: 'Align Left', class: 'nc-align-left-2' },
    { name: 'Ambulance', class: 'nc-ambulance' },
    { name: 'App', class: 'nc-app' },
    { name: 'Atom', class: 'nc-atom' },
    { name: 'Badge', class: 'nc-badge' },
    { name: 'Bag', class: 'nc-bag-16' },
    { name: 'Bank', class: 'nc-bank' },
    { name: 'Basket', class: 'nc-basket' },
    { name: 'Bell', class: 'nc-bell-55' },
    { name: 'Bold', class: 'nc-bold' },
    { name: 'Book Bookmark', class: 'nc-book-bookmark' },
    { name: 'Bookmark', class: 'nc-bookmark-2' },
    { name: 'Box 2', class: 'nc-box-2' },
    { name: 'Box', class: 'nc-box' },
    { name: 'Briefcase', class: 'nc-briefcase-24' },
    { name: 'Bulb', class: 'nc-bulb-63' },
    { name: 'Bullet List', class: 'nc-bullet-list-67' },
    { name: 'Bus Front', class: 'nc-bus-front-12' },
    { name: 'Button Pause', class: 'nc-button-pause' },
    { name: 'Button Play', class: 'nc-button-play' },
    { name: 'Button Power', class: 'nc-button-power' },
    { name: 'Calendar', class: 'nc-calendar-60' },
    { name: 'Camera Compact', class: 'nc-camera-compact' },
    { name: 'Caps Small', class: 'nc-caps-small' },
    { name: 'Cart Simple', class: 'nc-cart-simple' },
    { name: 'Chart Bar', class: 'nc-chart-bar-32' },
    { name: 'Chart Pie', class: 'nc-chart-pie-36' },
    { name: 'Chat', class: 'nc-chat-33' },
    { name: 'Check', class: 'nc-check-2' },
    { name: 'Circle', class: 'nc-circle-10' },
    { name: 'Cloud Download', class: 'nc-cloud-download-93' },
    { name: 'Cloud Upload', class: 'nc-cloud-upload-94' },
    { name: 'Compass', class: 'nc-compass-05' },
    { name: 'Controller Modern', class: 'nc-controller-modern' },
    { name: 'Credit Card', class: 'nc-credit-card' },
    { name: 'Delivery Fast', class: 'nc-delivery-fast' },
    { name: 'Diamond', class: 'nc-diamond' },
    { name: 'Email', class: 'nc-email-85' },
    { name: 'Favourite', class: 'nc-favourite-28' },
    { name: 'Glasses', class: 'nc-glasses-2' },
    { name: 'Globe 2', class: 'nc-globe-2' },
    { name: 'Globe', class: 'nc-globe' },
    { name: 'Hat', class: 'nc-hat-3' },
    { name: 'Headphones', class: 'nc-headphones' },
    { name: 'HTML5', class: 'nc-html5' },
    { name: 'Image', class: 'nc-image' },
    { name: 'Istanbul', class: 'nc-istanbul' },
    { name: 'Key', class: 'nc-key-25' },
    { name: 'Laptop', class: 'nc-laptop' },
    { name: 'Layout', class: 'nc-layout-11' },
    { name: 'Lock Circle Open', class: 'nc-lock-circle-open' },
    { name: 'Map Big', class: 'nc-map-big' },
    { name: 'Minimal Down', class: 'nc-minimal-down' },
    { name: 'Minimal Left', class: 'nc-minimal-left' },
    { name: 'Minimal Right', class: 'nc-minimal-right' },
    { name: 'Minimal Up', class: 'nc-minimal-up' },
    { name: 'Mobile', class: 'nc-mobile' },
    { name: 'Money Coins', class: 'nc-money-coins' },
    { name: 'Note', class: 'nc-note-03' },
    { name: 'Palette', class: 'nc-palette' },
    { name: 'Paper', class: 'nc-paper' },
    { name: 'Pin', class: 'nc-pin-3' },
    { name: 'Planet', class: 'nc-planet' },
    { name: 'Refresh', class: 'nc-refresh-69' },
    { name: 'Ruler Pencil', class: 'nc-ruler-pencil' },
    { name: 'Satisfied', class: 'nc-satisfied' },
    { name: 'Scissors', class: 'nc-scissors' },
    { name: 'Send', class: 'nc-send' },
    { name: 'Settings Gear', class: 'nc-settings-gear-65' },
    { name: 'Settings', class: 'nc-settings' },
    { name: 'Share', class: 'nc-share-66' },
    { name: 'Shop', class: 'nc-shop' },
    { name: 'Simple Add', class: 'nc-simple-add' },
    { name: 'Simple Delete', class: 'nc-simple-delete' },
    { name: 'Simple Remove', class: 'nc-simple-remove' },
    { name: 'Single', class: 'nc-single-02' },
    { name: 'Single Copy', class: 'nc-single-copy-04' },
    { name: 'Sound Wave', class: 'nc-sound-wave' },
    { name: 'Spaceship', class: 'nc-spaceship' },
    { name: 'Sun Fog', class: 'nc-sun-fog-29' },
    { name: 'Support', class: 'nc-support-17' },
    { name: 'Tablet', class: 'nc-tablet-2' },
    { name: 'Tag Content', class: 'nc-tag-content' },
    { name: 'Tap', class: 'nc-tap-01' },
    { name: 'Tie Bow', class: 'nc-tie-bow' },
    { name: 'Tile', class: 'nc-tile-56' },
    { name: 'Time Alarm', class: 'nc-time-alarm' },
    { name: 'Touch ID', class: 'nc-touch-id' },
    { name: 'Trophy', class: 'nc-trophy' },
    { name: 'TV', class: 'nc-tv-2' },
    { name: 'Umbrella', class: 'nc-umbrella-13' },
    { name: 'User Run', class: 'nc-user-run' },
    { name: 'Vector', class: 'nc-vector' },
    { name: 'Watch Time', class: 'nc-watch-time' },
    { name: 'World', class: 'nc-world-2' },
    { name: 'Zoom Split', class: 'nc-zoom-split' }
  ];
} 